// Register definitions: fields drive both the table columns and the entry form.
// A "Sl. No." auto serial column is rendered by the table (not stored).
// field types: text, number, date, textarea, select, student (ref), course (ref)
const sel = (name, label, options, opts = {}) => ({ name, label, type: "select", options, ...opts });
const t = (name, label, opts = {}) => ({ name, label, type: "text", ...opts });
const n = (name, label, opts = {}) => ({ name, label, type: "number", ...opts });
const d = (name, label, opts = {}) => ({ name, label, type: "date", ...opts });
const ta = (name, label, opts = {}) => ({ name, label, type: "textarea", ...opts });

export const REGISTERS = {
  // ---------------- STUDENT ----------------
  admission: {
    label: "Admission Register", group: "Student Registers", icon: "GraduationCap",
    subtitle: "Master student record",
    fields: [
      d("joining_date", "Joining Date"),
      t("student_id", "Student ID", { auto: true, hint: "Auto-generated" }),
      t("name", "Student Name", { required: true }),
      d("dob", "Date of Birth"),
      sel("gender", "Gender", ["Male", "Female", "Other"]),
      ta("address", "Address"),
      t("mobile", "Mobile Number"),
      t("guardian_name", "Parent/Guardian Name"),
      t("parent_mobile", "Parent Mobile"),
      t("id_proof", "ID Proof"),
      { name: "course", label: "Course Name", type: "course", required: true },
      t("batch_id", "Batch ID"),
      sel("mode", "Mode", ["Offline", "Online"]),
      n("course_fees", "Course Fees"),
      t("course_duration", "Course Duration"),
      sel("status", "Admission Status", ["active", "dropped", "completed"], { default: "active" }),
      t("photograph", "Photograph (URL)"),
      t("remarks", "Remarks"),
    ],
  },
  fee: {
    label: "Fee Register", group: "Student Registers", icon: "Wallet",
    fields: [
      { name: "student_id", label: "Student ID", type: "student", required: true },
      t("student_name", "Student Name"),
      { name: "course", label: "Course Name", type: "course" },
      t("batch_id", "Batch ID"),
      n("total_fees", "Total Fees"),
      n("amount_paid", "Amount Paid"),
      n("balance", "Balance"),
      d("payment_date", "Payment Date"),
      sel("payment_mode", "Payment Mode", ["Cash", "Card", "UPI", "Bank", "Cheque"]),
      t("transaction_id", "Transaction ID / Receipt No."),
      t("received_by", "Received By"),
      t("remarks", "Remarks"),
    ],
  },
  course: {
    label: "Course Register", group: "Student Registers", icon: "BookOpen",
    subtitle: "Course catalogue (used for dropdowns & teacher assignment)",
    fields: [
      t("name", "Course Name", { required: true }),
      t("code", "Code"),
      t("duration", "Duration"),
      t("level", "Level"),
      t("fee_structure", "Fee Structure"),
      t("batch_timings", "Batch Timings"),
      n("seats", "Seats"),
    ],
  },
  coursewise: {
    label: "Course Wise Register", group: "Student Registers", icon: "BookMarked",
    fields: [
      d("joining_date", "Joining Date"),
      { name: "student_id", label: "Student ID", type: "student", required: true },
      t("student_name", "Student Name"),
      t("batch_id", "Batch ID"),
      { name: "course", label: "Course Name", type: "course" },
      t("level", "Level"),
      t("duration", "Duration"),
      sel("video_access", "Video Access", ["Yes", "No"]),
      t("attendance_pct", "Attendance %"),
      t("remarks", "Remarks"),
    ],
  },
  attendance: {
    label: "Student Attendance", group: "Student Registers", icon: "CalendarCheck",
    subtitle: "Teacher-marked; admin can edit",
    fields: [
      d("date", "Date", { required: true }),
      { name: "student_id", label: "Student ID", type: "student" },
      t("student_name", "Student Name"),
      t("batch", "Batch"),
      t("in_time", "In Time"),
      t("out_time", "Out Time"),
      sel("status", "Attendance Status", ["present", "absent", "late"], { default: "present" }),
      t("faculty", "Faculty"),
      t("remark", "Remarks"),
    ],
  },
  certificate: {
    label: "Certificate Issue", group: "Student Registers", icon: "Award",
    fields: [
      t("certificate_no", "Certificate Number", { auto: true, hint: "Auto-generated" }),
      d("issue_date", "Date of Issue"),
      { name: "student_id", label: "Student ID", type: "student", required: true },
      t("student_name", "Student Name"),
      { name: "course", label: "Course", type: "course" },
      t("batch_id", "Batch ID"),
      t("course_duration", "Course Duration"),
      d("completion_date", "Date of Completion"),
      sel("mode_of_issue", "Mode of Issue", ["Offline", "Online", "Post"]),
      t("issued_by", "Issued By"),
      t("remarks", "Remarks"),
    ],
  },
  placement: {
    label: "Placement Register", group: "Student Registers", icon: "Briefcase",
    fields: [
      { name: "student_id", label: "Student ID", type: "student", required: true },
      t("student_name", "Student Name"),
      { name: "course", label: "Course", type: "course" },
      d("completion_date", "Completion Date"),
      sel("job_type", "Job / Self Employed", ["Job", "Self Employed"]),
      t("company", "Company / Business Name"),
      t("designation", "Designation"),
      t("salary", "Salary / Income"),
      d("joining_date", "Joining Date"),
      t("remarks", "Remarks"),
    ],
  },
  scholarship: {
    label: "Scholarship & Free Class", group: "Student Registers", icon: "HandHeart",
    fields: [
      d("date", "Date"),
      { name: "student_id", label: "Student ID", type: "student", required: true },
      t("student_name", "Student Name"),
      { name: "course", label: "Course", type: "course" },
      t("batch_id", "Batch ID"),
      n("course_fee", "Course Fee"),
      n("scholarship_amount", "Scholarship Amount"),
      n("student_paid", "Student Paid"),
      t("approved_by", "Approved By"),
      t("remarks", "Remarks"),
    ],
  },

  // ---------------- STAFF ----------------
  staff: {
    label: "Staff Register", group: "Staff Registers", icon: "Users",
    fields: [
      t("staff_id", "Staff ID", { auto: true, hint: "Auto-generated" }),
      t("name", "Staff Name", { required: true }),
      t("designation", "Designation"),
      t("department", "Department"),
      t("contact", "Contact Number"),
      t("email", "Email"),
      d("joining_date", "Date of Joining"),
      sel("employment_type", "Employment Type", ["Full-time", "Part-time", "Contract"]),
      n("salary", "Salary"),
      sel("status", "Status", ["active", "inactive"], { default: "active" }),
      t("remarks", "Remarks"),
    ],
  },
  faculty_attendance: {
    label: "Faculty Attendance", group: "Staff Registers", icon: "ClipboardCheck",
    fields: [
      d("date", "Date", { required: true }),
      t("staff_id", "Staff ID"),
      t("staff_name", "Staff Name"),
      t("department", "Department"),
      t("in_time", "In Time"),
      t("out_time", "Out Time"),
      t("working_hours", "Working Hours"),
      sel("status", "Attendance Status", ["present", "absent", "leave"], { default: "present" }),
      t("remark", "Remarks"),
    ],
  },
  salary: {
    label: "Salary Register", group: "Staff Registers", icon: "BadgeDollarSign",
    fields: [
      t("staff_id", "Staff ID", { required: true }),
      t("staff_name", "Staff Name"),
      t("designation", "Designation"),
      t("month", "Month"),
      n("gross_salary", "Gross Salary"),
      n("deduction", "Deduction"),
      n("net_salary", "Net Salary"),
      sel("payment_mode", "Payment Mode", ["Cash", "Bank", "UPI", "Cheque"]),
      d("payment_date", "Payment Date"),
      t("transaction_id", "Transaction ID"),
      t("remarks", "Remarks"),
    ],
  },

  // ---------------- ACCOUNTS ----------------
  cashbook: {
    label: "Cash Register", group: "Accounts Registers", icon: "Coins",
    fields: [
      d("date", "Date", { required: true }),
      t("voucher_no", "Voucher No."),
      t("particulars", "Particulars"),
      n("receipt", "Receipt"),
      n("payment", "Payment"),
      n("balance", "Balance", { auto: true, hint: "Auto-calculated" }),
    ],
  },
  bankbook: {
    label: "Bank Register", group: "Accounts Registers", icon: "Landmark",
    fields: [
      d("date", "Date", { required: true }),
      t("voucher_no", "Voucher No."),
      t("particulars", "Particulars"),
      n("receipt", "Receipt"),
      n("payment", "Payment"),
      n("balance", "Balance", { auto: true, hint: "Auto-calculated" }),
    ],
  },
  income: {
    label: "Income Register", group: "Accounts Registers", icon: "TrendingUp",
    fields: [
      d("date", "Date", { required: true }),
      t("voucher_no", "Voucher No."),
      t("income_head", "Income Head"),
      t("particulars", "Particulars"),
      n("amount", "Amount"),
    ],
  },
  expense: {
    label: "Expense Register", group: "Accounts Registers", icon: "TrendingDown",
    fields: [
      d("date", "Date", { required: true }),
      t("voucher_no", "Voucher No."),
      t("expense_head", "Expense Head"),
      t("particulars", "Particulars"),
      n("amount", "Amount"),
    ],
  },
  purchase: {
    label: "Purchase Register", group: "Accounts Registers", icon: "ShoppingCart",
    fields: [
      d("date", "Date", { required: true }),
      t("invoice_no", "Invoice No."),
      t("supplier_name", "Supplier Name"),
      t("supplier_gstin", "Supplier GSTIN"),
      n("taxable_value", "Taxable Value"),
      n("cgst", "CGST"),
      n("sgst", "SGST"),
      n("igst", "IGST"),
      n("invoice_total", "Invoice Total"),
      t("itc", "ITC"),
      t("remarks", "Remarks"),
    ],
  },
  receipt: {
    label: "Receipt Register", group: "Accounts Registers", icon: "ReceiptText",
    fields: [
      t("receipt_no", "Receipt No.", { auto: true, hint: "Auto-generated" }),
      d("date", "Date", { required: true }),
      t("received_from", "Received From"),
      t("purpose", "Purpose"),
      n("amount", "Amount"),
      sel("payment_mode", "Payment Mode", ["Cash", "Card", "UPI", "Bank", "Cheque"]),
      t("transaction_id", "Transaction ID"),
      t("remarks", "Remarks"),
    ],
  },

  // ---------------- ADMINISTRATIVE ----------------
  correspondence: {
    label: "Correspondence Register", group: "Administrative Registers", icon: "Mail",
    fields: [
      d("date", "Date", { required: true }),
      t("reference_no", "Reference No."),
      t("party", "Received From / Sent To"),
      t("subject", "Subject"),
      sel("mode", "Mode", ["In", "Out"]),
      t("remarks", "Remarks"),
    ],
  },
  visitor: {
    label: "Visitor Register", group: "Administrative Registers", icon: "UserCheck",
    fields: [
      d("date", "Date", { required: true }),
      t("name", "Visitor Name", { required: true }),
      t("mobile", "Mobile Number"),
      t("organisation", "Organisation"),
      t("purpose", "Purpose of Visit"),
      t("person_to_meet", "Person to Meet"),
      t("in_time", "In Time"),
      t("out_time", "Out Time"),
      t("id_proof", "ID Proof"),
      t("signature", "Signature"),
      t("remarks", "Remarks"),
    ],
  },
  asset: {
    label: "Asset Register", group: "Administrative Registers", icon: "Package",
    fields: [
      t("asset_id", "Asset ID", { auto: true, hint: "Auto-generated" }),
      d("purchase_date", "Purchase Date"),
      t("name", "Asset Name", { required: true }),
      t("category", "Category"),
      t("brand", "Brand"),
      t("model", "Model"),
      t("serial_number", "Serial Number"),
      t("supplier_name", "Supplier Name"),
      t("invoice_no", "Invoice No."),
      n("cost", "Cost"),
      n("quantity", "Quantity"),
      d("warranty_expiry", "Warranty Expiry"),
      t("location", "Location"),
      t("assigned_to", "Assigned To"),
      sel("condition", "Condition", ["Good", "Fair", "Poor"]),
      sel("status", "Status", ["In Use", "In Store", "Under Repair", "Disposed"]),
      d("disposal_date", "Disposal Date"),
      t("remarks", "Remarks"),
    ],
  },
  maintenance: {
    label: "Maintenance Register", group: "Administrative Registers", icon: "Wrench",
    fields: [
      d("date", "Date", { required: true }),
      t("equipment", "Equipment"),
      t("complaint", "Complaint"),
      t("service_done", "Service Done"),
      t("vendor", "Vendor"),
      n("cost", "Cost"),
      d("next_service_date", "Next Service Date"),
      t("remarks", "Remarks"),
    ],
  },
  firesafety: {
    label: "Fire Safety Register", group: "Administrative Registers", icon: "Flame",
    fields: [
      d("date", "Date", { required: true }),
      t("equipment", "Equipment"),
      t("location", "Location"),
      d("last_inspection_date", "Last Inspection Date"),
      d("next_due_date", "Next Due Date"),
      sel("status", "Status", ["OK", "Needs Attention", "Expired"]),
      t("remarks", "Remarks"),
    ],
  },
  complaint: {
    label: "Complaint Register", group: "Administrative Registers", icon: "Megaphone",
    fields: [
      d("date", "Date", { required: true }),
      t("complaint_no", "Complaint No.", { auto: true, hint: "Auto-generated" }),
      t("name", "Name"),
      t("category", "Category"),
      ta("details", "Complaint Details"),
      t("assigned_to", "Assigned To"),
      sel("status", "Status", ["Open", "In Progress", "Resolved"], { default: "Open" }),
      d("resolution_date", "Resolution Date"),
      t("remarks", "Remarks"),
    ],
  },
  stock: {
    label: "Stock Register", group: "Administrative Registers", icon: "Boxes",
    fields: [
      d("date", "Date", { required: true }),
      t("item_name", "Item Name", { required: true }),
      t("category", "Category"),
      n("quantity_in", "Quantity In"),
      n("quantity_out", "Quantity Out"),
      n("balance", "Balance"),
      t("unit", "Unit"),
      t("location", "Location"),
      t("remarks", "Remarks"),
    ],
  },
  library: {
    label: "Library Register", group: "Administrative Registers", icon: "Library",
    optional: true,
    fields: [
      d("date", "Date"),
      t("book_title", "Book Title", { required: true }),
      t("author", "Author"),
      t("isbn", "ISBN"),
      t("category", "Category"),
      t("issued_to", "Issued To"),
      d("issue_date", "Issue Date"),
      d("return_date", "Return Date"),
      sel("status", "Status", ["Available", "Issued", "Lost"]),
      t("remarks", "Remarks"),
    ],
  },
  lostfound: {
    label: "Lost & Found Register", group: "Administrative Registers", icon: "PackageSearch",
    optional: true,
    fields: [
      d("date", "Date"),
      t("item", "Item", { required: true }),
      ta("description", "Description"),
      sel("type", "Lost / Found", ["Lost", "Found"]),
      t("reported_by", "Reported By"),
      t("location", "Location"),
      sel("status", "Status", ["Open", "Claimed", "Returned"]),
      t("handed_to", "Handed To"),
      t("remarks", "Remarks"),
    ],
  },
  vehicle: {
    label: "Vehicle Register", group: "Administrative Registers", icon: "Car",
    optional: true,
    fields: [
      d("date", "Date"),
      t("vehicle_no", "Vehicle No.", { required: true }),
      t("type", "Type"),
      t("driver", "Driver"),
      t("purpose", "Purpose"),
      t("out_time", "Out Time"),
      t("in_time", "In Time"),
      n("km_out", "KM Out"),
      n("km_in", "KM In"),
      t("remarks", "Remarks"),
    ],
  },
};

export const GROUPS = [
  "Student Registers",
  "Staff Registers",
  "Accounts Registers",
  "Administrative Registers",
];
